In [88]:
import os
import requests
import numpy as np
import pandas as pd
import seaborn as sns

In [89]:
df = pd.read_excel(r'/Users/kanimozhivelusamy/Downloads/tech_layoffs.xlsx')
df.head()

,#,Company,Location_HQ,Country,Continent,Laid_Off,Date_layoffs,Percentage,Company_Size_before_Layoffs,Company_Size_after_layoffs,Industry,Stage,Money_Raised_in_$_mil,Year,lat,lng
0,3,ShareChat,Bengaluru,India,Asia,200,2023-12-20,15.0,1333,1133,Consumer,Series H,$1700,2023,12.97194,77.59369
1,4,InSightec,Haifa,Israel,Asia,100,2023-12-19,20.0,500,400,Healthcare,Unknown,$733,2023,32.81841,34.98850
2,6,Enphase Energy,San Francisco Bay Area,USA,North America,350,2023-12-18,10.0,3500,3150,Energy,Post-IPO,$116,2023,37.54827,-121.98857
3,7,Udaan,Bengaluru,India,Asia,100,2023-12-18,10.0,1000,900,Retail,Unknown,1500,2023,12.97194,77.59369
4,14,Cruise,San Francisco Bay Area,USA,North America,900,2023-12-14,24.0,3750,2850,Transportation,Acquired,$15000,2023,37.77493,-122.41942

In [90]:
df['Date_layoffs'] = pd.to_datetime(df['Date_layoffs'])

df_filtered = df[(df['Date_layoffs'].dt.year >= 2022) & (df['Date_layoffs'].dt.year <= 2024) & (df['Country'] == 'USA')]

print(df_filtered)

df_filtered.to_csv('df_2022_to_2024_layoffs_USA_filtered.csv', index=False)

         #                Company             Location_HQ Country  \
2        6         Enphase Energy  San Francisco Bay Area     USA
4       14                 Cruise  San Francisco Bay Area     USA
5       16                   Bolt  San Francisco Bay Area     USA
6       20                Invitae  San Francisco Bay Area     USA
7       21                   Etsy           New York City     USA
...    ...                    ...                     ...     ...
1410  3283        Rent the Runway           New York City     USA
1411  3284                 Humane  San Francisco Bay Area     USA
1412  3285                  Unity  San Francisco Bay Area     USA
1415  3288  NanoString Technology                 Seattle     USA
1417  3290              Frontdesk               Milwaukee     USA

          Continent  Laid_Off Date_layoffs  Percentage  \
2     North America       350   2023-12-18        10.0
4     North America       900   2023-12-14        24.0
5     North America       130   2023-12-14        29.0
6     North America       235   2023-12-13        15.0
7     North America       225   2023-12-13        11.0
...             ...       ...          ...         ...
1410  North America        37   2024-09-01        10.0
1411  North America        10   2024-09-01         4.0
1412  North America      1800   2024-08-01        25.0
1415  North America        50   2024-08-01         9.0
1417  North America       200   2024-02-01       100.0

      Company_Size_before_Layoffs  Company_Size_after_layoffs        Industry  \
2                            3500                        3150          Energy
4                            3750                        2850  Transportation
5                             450                         320         Finance
6                            1567                        1332      Healthcare
7                            2045                        1820          Retail
...                           ...                         ...             ...
1410                          370                         333          Retail
1411                          250                         240        Hardware
1412                         7200                        5400           Other
1415                          556                         506      Healthcare
1417                          200                           0          Travel

         Stage Money_Raised_in_$_mil  Year       lat        lng
2     Post-IPO                  $116  2023  37.54827 -121.98857
4     Acquired                $15000  2023  37.77493 -122.41942
5     Series E                 $1300  2023  37.77493 -122.41942
6     Post-IPO                  2500  2023  37.77493 -122.41942
7     Post-IPO                   $97  2023  40.71427  -74.00597
...        ...                   ...   ...       ...        ...
1410  Post-IPO                  $526  2024  40.71427  -74.00597
1411  Series C                  $230  2024  37.77493 -122.41942
1412  Post-IPO                 $1300  2024  37.77493 -122.41942
1415  Post-IPO                  $826  2024  47.60621 -122.33207
1417   Unknown                   $26  2024  43.03890  -87.90647

[658 rows x 16 columns]

In [91]:
df_filtered.head(1000)

,#,Company,Location_HQ,Country,Continent,Laid_Off,Date_layoffs,Percentage,Company_Size_before_Layoffs,Company_Size_after_layoffs,Industry,Stage,Money_Raised_in_$_mil,Year,lat,lng
2,6,Enphase Energy,San Francisco Bay Area,USA,North America,350,2023-12-18,10.0,3500,3150,Energy,Post-IPO,$116,2023,37.54827,-121.98857
4,14,Cruise,San Francisco Bay Area,USA,North America,900,2023-12-14,24.0,3750,2850,Transportation,Acquired,$15000,2023,37.77493,-122.41942
5,16,Bolt,San Francisco Bay Area,USA,North America,130,2023-12-14,29.0,450,320,Finance,Series E,$1300,2023,37.77493,-122.41942
6,20,Invitae,San Francisco Bay Area,USA,North America,235,2023-12-13,15.0,1567,1332,Healthcare,Post-IPO,2500,2023,37.77493,-122.41942
7,21,Etsy,New York City,USA,North America,225,2023-12-13,11.0,2045,1820,Retail,Post-IPO,$97,2023,40.71427,-74.00597
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1410,3283,Rent the Runway,New York City,USA,North America,37,2024-09-01,10.0,370,333,Retail,Post-IPO,$526,2024,40.71427,-74.00597
1411,3284,Humane,San Francisco Bay Area,USA,North America,10,2024-09-01,4.0,250,240,Hardware,Series C,$230,2024,37.77493,-122.41942
1412,3285,Unity,San Francisco Bay Area,USA,North America,1800,2024-08-01,25.0,7200,5400,Other,Post-IPO,$1300,2024,37.77493,-122.41942
1415,3288,NanoString Technology,Seattle,USA,North America,50,2024-08-01,9.0,556,506,Healthcare,Post-IPO,$826,2024,47.60621,-122.33207
1417,3290,Frontdesk,Milwaukee,USA,North America,200,2024-02-01,100.0,200,0,Travel,Unknown,$26,2024,43.03890,-87.90647

In [92]:
layoff_df = pd.read_csv(r'/Users/kanimozhivelusamy/Downloads/df_2022_to_2024_layoffs_USA_filtered.csv')
company_names_df = pd.read_excel(r'/Users/kanimozhivelusamy/Downloads/Company_2024.xlsx')

company_names_list = company_names_df['Company'].tolist()

filtered_layoff_df = layoff_df[layoff_df['Company'].isin(company_names_list)]

filtered_layoff_df.to_csv('filtered_layoff_details_1.csv', index=False)

In [87]:
filtered_layoff_df.head(100)

,#,Company,Location_HQ,Country,Continent,Laid_Off,Date_layoffs,Percentage,Company_Size_before_Layoffs,Company_Size_after_layoffs,Industry,Stage,Money_Raised_in_$_mil,Year,lat,lng
0,6,Enphase Energy,San Francisco Bay Area,USA,North America,350,2023-12-18,10.000000,3500,3150,Energy,Post-IPO,$116,2023,37.54827,-121.98857
4,21,Etsy,New York City,USA,North America,225,2023-12-13,11.000000,2045,1820,Retail,Post-IPO,$97,2023,40.71427,-74.00597
8,56,Unity,San Francisco Bay Area,USA,North America,265,2023-11-28,4.000000,6625,6360,Other,Post-IPO,$1300,2023,37.77493,-122.41942
11,91,TripAdvisor,Boston,USA,North America,125,2023-11-12,4.000000,3125,3000,Travel,Post-IPO,$3,2023,42.35843,-71.05977
55,311,SecureWorks,Atlanta,USA,North America,300,2023-08-14,15.000000,2000,1700,Security,Post-IPO,$83,2023,33.74900,-84.38798
57,328,Thoughtworks,Chicago,USA,North America,579,2023-08-08,5.000000,11580,11001,Other,Post-IPO,$748,2023,41.85003,-87.65005
90,504,Uber,San Francisco Bay Area,USA,North America,200,2023-06-21,0.996165,20077,19877,Transportation,Post-IPO,$25200,2023,37.77493,-122.41942
95,530,TrueCar,Los Angeles,USA,North America,102,2023-06-14,24.000000,425,323,Transportation,Post-IPO,$340,2023,34.05223,-118.24368
99,540,Chegg,San Francisco Bay Area,USA,North America,80,2023-06-12,4.000000,2000,1920,Education,Post-IPO,$227,2023,37.35411,-121.95524
106,562,Reddit,San Francisco Bay Area,USA,North America,90,2023-06-06,5.000000,1800,1710,Consumer,Series F,$1300,2023,37.77493,-122.41942
119,628,Lemonade,New York City,USA,North America,45,2023-05-16,3.000000,1500,1455,Finance,Post-IPO,$481,2023,40.71427,-74.00597
129,667,Unity,San Francisco Bay Area,USA,North America,600,2023-05-03,8.000000,7500,6900,Other,Post-IPO,$1300,2023,37.77493,-122.41942
135,688,Dropbox,San Francisco Bay Area,USA,North America,500,2023-04-27,16.000000,3125,2625,Other,Post-IPO,$1700,2023,37.77493,-122.41942
137,690,Vroom,New York City,USA,North America,120,2023-04-27,11.000000,1091,971,Transportation,Post-IPO,$1300,2023,40.71427,-74.00597
144,709,Lyft,San Francisco Bay Area,USA,North America,1072,2023-04-21,26.000000,4123,3051,Transportation,Post-IPO,$4900,2023,37.77493,-122.41942
146,712,BuzzFeed,New York City,USA,North America,180,2023-04-20,15.000000,1200,1020,Media,Post-IPO,$696,2023,40.71427,-74.00597
149,721,Opendoor,San Francisco Bay Area,USA,North America,560,2023-04-18,22.000000,2545,1985,Real Estate,Post-IPO,$1900,2023,37.77493,-122.41942
170,800,Lucid Motors,San Francisco Bay Area,USA,North America,1300,2023-03-28,18.000000,7222,5922,Transportation,Post-IPO,$8300,2023,37.52966,-122.04024
174,829,Amazon,Seattle,USA,North America,9000,2023-03-20,2.295918,392000,383000,Retail,Post-IPO,$108,2023,47.60621,-122.33207
179,846,Meta,San Francisco Bay Area,USA,North America,10000,2023-03-14,13.584117,73615,63615,Consumer,Post-IPO,$26000,2023,37.45383,-122.18219
189,895,Thoughtworks,Chicago,USA,North America,500,2023-03-01,4.000000,12500,12000,Other,Post-IPO,$748,2023,41.85003,-87.65005
201,953,Micron,Boise,USA,North America,2400,2023-02-17,5.000000,48000,45600,Hardware,Post-IPO,$50,2023,43.61350,-116.20345
225,1025,Zoom,San Francisco Bay Area,USA,North America,1300,2023-02-07,15.000000,8667,7367,Other,Post-IPO,$276,2023,37.33939,-121.89496
226,1026,eBay,San Francisco Bay Area,USA,North America,500,2023-02-07,4.000000,12500,12000,Retail,Post-IPO,$1200,2023,37.33939,-121.89496
227,1027,SecureWorks,Atlanta,USA,North America,212,2023-02-07,9.000000,2356,2144,Security,Post-IPO,$83,2023,33.74900,-84.38798
241,1084,PayPal,San Francisco Bay Area,USA,North America,2000,2023-01-31,7.000000,28571,26571,Finance,Post-IPO,$216,2023,37.33939,-121.89496
257,1171,Google,San Francisco Bay Area,USA,North America,12000,2023-01-20,6.000000,200000,188000,Consumer,Post-IPO,$26,2023,37.38605,-122.08385
264,1204,Microsoft,Seattle,USA,North America,10000,2023-01-18,5.000000,200000,190000,Other,Post-IPO,$1,2023,47.60621,-122.33207
266,1207,Vroom,New York City,USA,North America,275,2023-01-18,20.000000,1375,1100,Transportation,Post-IPO,1300,2023,40.71427,-74.00597
274,1229,Unity,San Francisco Bay Area,USA,North America,284,2023-01-17,3.000000,9467,9183,Other,Post-IPO,$1300,2023,37.77493,-122.41942
296,1346,Amazon,Seattle,USA,North America,8000,2023-01-04,2.000000,400000,392000,Retail,Post-IPO,$108,2023,47.60621,-122.33207
302,1359,Micron,Boise,USA,North America,4800,2023-01-01,10.000000,48000,43200,Hardware,Post-IPO,$50,2023,43.61350,-116.20345
329,1461,BuzzFeed,New York City,USA,North America,180,2022-12-06,12.000000,1500,1320,Media,Post-IPO,$696,2022,40.71427,-74.00597
337,1498,DoorDash,San Francisco Bay Area,USA,North America,1250,2022-11-30,6.000000,20833,19583,Food,Post-IPO,$2500,2022,37.77493,-122.41942
348,1586,Amazon,Seattle,USA,North America,10000,2022-11-16,3.000000,333333,323333,Retail,Post-IPO,$108,2022,47.60621,-122.33207
349,1587,Cisco,San Francisco Bay Area,USA,North America,4100,2022-11-16,5.000000,82000,77900,Infrastructure,Post-IPO,$2,2022,37.33939,-121.89496
371,1654,Meta,San Francisco Bay Area,USA,North America,11000,2022-11-09,13.000000,84615,73615,Consumer,Post-IPO,$26000,2022,37.45383,-122.18219
385,1694,Lyft,San Francisco Bay Area,USA,North America,700,2022-11-03,13.000000,5385,4685,Transportation,Post-IPO,$4900,2022,37.77493,-122.41942
387,1706,Opendoor,San Francisco Bay Area,USA,North America,550,2022-11-02,18.000000,3056,2506,Real Estate,Post-IPO,1900,2022,37.77493,-122.41942
395,1735,Amazon,Seattle,USA,North America,150,2022-10-28,0.044980,333483,333333,Retail,Post-IPO,$108,2022,47.60621,-122.33207
509,2154,Lyft,San Francisco Bay Area,USA,North America,60,2022-07-20,2.000000,3000,2940,Transportation,Post-IPO,$4900,2022,37.77493,-122.41942
544,2263,Unity,San Francisco Bay Area,USA,North America,200,2022-06-29,4.000000,5000,4800,Other,Post-IPO,$1300,2022,37.77493,-122.41942
558,2303,Netflix,San Francisco Bay Area,USA,North America,300,2022-06-23,3.000000,10000,9700,Media,Post-IPO,$121900,2022,37.22661,-121.97468
615,2492,Netflix,San Francisco Bay Area,USA,North America,150,2022-05-17,1.000000,15000,14850,Media,Post-IPO,$121900,2022,37.22661,-121.97468
621,2510,Vroom,New York City,USA,North America,270,2022-05-09,14.000000,1929,1659,Transportation,Post-IPO,1300,2022,40.71427,-74.00597
654,2630,Dropbox,San Francisco Bay Area,USA,North America,315,2021-01-13,15.000000,2100,1785,Other,Post-IPO,$1700,2021,37.77493,-122.41942
693,2771,TrueCar,Los Angeles,USA,North America,219,2020-05-28,30.000000,730,511,Transportation,Post-IPO,$340,2020,34.05223,-118.24368
703,2796,Uber,San Francisco Bay Area,USA,North America,3000,2020-05-18,13.000000,23077,20077,Transportation,Post-IPO,$24700,2020,37.77493,-122.41942
719,2842,Uber,San Francisco Bay Area,USA,North America,3700,2020-05-06,14.000000,26429,22729,Transportation,Post-IPO,$24700,2020,37.77493,-122.41942
730,2884,Lyft,San Francisco Bay Area,USA,North America,982,2020-04-29,17.000000,5776,4794,Transportation,Post-IPO,$4900,2020,37.77493,-122.41942
734,2891,TripAdvisor,Boston,USA,North America,900,2020-04-28,25.000000,3600,2700,Travel,Post-IPO,$3,2020,42.35843,-71.05977
768,2975,Opendoor,San Francisco Bay Area,USA,North America,600,2020-04-15,35.000000,1714,1114,Real Estate,Series E,$1500,2020,37.77493,-122.41942
896,3277,Google,San Francisco Bay Area,USA,North America,1000,2024-10-01,0.531915,188000,187000,Consumer,Post-IPO,$26,2024,37.38605,-122.08385
902,3285,Unity,San Francisco Bay Area,USA,North America,1800,2024-08-01,25.000000,7200,5400,Other,Post-IPO,$1300,2024,37.77493,-122.41942

In [94]:
# Mapping of company names to be replaced
replacement_mapping = {
    "Google": "Alphabet Inc Class C",
    "Amazon": "Amazon.com Inc",
    "BuzzFeed": "Buzzfeed Inc",
    "Chegg": "Chegg Inc",
    "Cisco": "Cisco Systems Inc",
    "DoorDash": "DoorDash Inc",
    "Dropbox": "Dropbox Inc",
    "eBay": "eBay Inc",
    "Enphase Energy": "Enphase Energy Inc",
    "Etsy": "Etsy Inc",
    "Lemonade": "Lemonade Inc",
    "Lucid Motors": "Lucid Group Inc",
    "Lyft": "LYFT Inc",
    "Meta": "Meta Platforms Inc",
    "Micron": "Micron Technology Inc",
    "Microsoft": "Microsoft Corp",
    "Netflix": "Netflix Inc",
    "Opendoor": "Opendoor Technologies Inc",
    "PayPal": "PayPal Holdings Inc",
    "Reddit": "Reddit Inc",
    "SecureWorks": "SecureWorks Corp",
    "Thoughtworks": "Thoughtworks Holding Inc",
    "TripAdvisor": "Tripadvisor Inc",
    "TrueCar": "TrueCar Inc",
    "Uber": "Uber Technologies Inc",
    "Unity": "Unity Software Inc",
    "Vroom": "Vroom Inc",
    "Wayfair": "Wayfair Inc",
    "Workday": "Workday Inc",
    "Zoom": "Zoom Video Communications Inc",
}

# Replace CompanyName column using the replacement mapping
filtered_layoff_df['Company'] = filtered_layoff_df['Company'].replace(replacement_mapping)

# Display the updated DataFrame
print(filtered_layoff_df)

        #                        Company             Location_HQ Country  \
0       6             Enphase Energy Inc  San Francisco Bay Area     USA
4      21                       Etsy Inc           New York City     USA
8      56             Unity Software Inc  San Francisco Bay Area     USA
11     91                Tripadvisor Inc                  Boston     USA
55    311               SecureWorks Corp                 Atlanta     USA
57    328       Thoughtworks Holding Inc                 Chicago     USA
90    504          Uber Technologies Inc  San Francisco Bay Area     USA
95    530                    TrueCar Inc             Los Angeles     USA
99    540                      Chegg Inc  San Francisco Bay Area     USA
106   562                     Reddit Inc  San Francisco Bay Area     USA
119   628                   Lemonade Inc           New York City     USA
129   667             Unity Software Inc  San Francisco Bay Area     USA
135   688                    Dropbox Inc  San Francisco Bay Area     USA
137   690                      Vroom Inc           New York City     USA
144   709                       LYFT Inc  San Francisco Bay Area     USA
146   712                   Buzzfeed Inc           New York City     USA
149   721      Opendoor Technologies Inc  San Francisco Bay Area     USA
170   800                Lucid Group Inc  San Francisco Bay Area     USA
174   829                 Amazon.com Inc                 Seattle     USA
179   846             Meta Platforms Inc  San Francisco Bay Area     USA
189   895       Thoughtworks Holding Inc                 Chicago     USA
201   953          Micron Technology Inc                   Boise     USA
225  1025  Zoom Video Communications Inc  San Francisco Bay Area     USA
226  1026                       eBay Inc  San Francisco Bay Area     USA
227  1027               SecureWorks Corp                 Atlanta     USA
241  1084            PayPal Holdings Inc  San Francisco Bay Area     USA
257  1171           Alphabet Inc Class C  San Francisco Bay Area     USA
264  1204                 Microsoft Corp                 Seattle     USA
266  1207                      Vroom Inc           New York City     USA
274  1229             Unity Software Inc  San Francisco Bay Area     USA
296  1346                 Amazon.com Inc                 Seattle     USA
302  1359          Micron Technology Inc                   Boise     USA
329  1461                   Buzzfeed Inc           New York City     USA
337  1498                   DoorDash Inc  San Francisco Bay Area     USA
348  1586                 Amazon.com Inc                 Seattle     USA
349  1587              Cisco Systems Inc  San Francisco Bay Area     USA
371  1654             Meta Platforms Inc  San Francisco Bay Area     USA
385  1694                       LYFT Inc  San Francisco Bay Area     USA
387  1706      Opendoor Technologies Inc  San Francisco Bay Area     USA
395  1735                 Amazon.com Inc                 Seattle     USA
509  2154                       LYFT Inc  San Francisco Bay Area     USA
544  2263             Unity Software Inc  San Francisco Bay Area     USA
558  2303                    Netflix Inc  San Francisco Bay Area     USA
615  2492                    Netflix Inc  San Francisco Bay Area     USA
621  2510                      Vroom Inc           New York City     USA
649  3277           Alphabet Inc Class C  San Francisco Bay Area     USA
655  3285             Unity Software Inc  San Francisco Bay Area     USA

         Continent  Laid_Off Date_layoffs  Percentage  \
0    North America       350   2023-12-18   10.000000
4    North America       225   2023-12-13   11.000000
8    North America       265   2023-11-28    4.000000
11   North America       125   2023-11-12    4.000000
55   North America       300   2023-08-14   15.000000
57   North America       579   2023-08-08    5.000000
90   North America       200   2023-06-21    0.996165
95   North America       102   2023-06-14   24.000000
99   North America        80   2023-06-12    4.000000
106  North America        90   2023-06-06    5.000000
119  North America        45   2023-05-16    3.000000
129  North America       600   2023-05-03    8.000000
135  North America       500   2023-04-27   16.000000
137  North America       120   2023-04-27   11.000000
144  North America      1072   2023-04-21   26.000000
146  North America       180   2023-04-20   15.000000
149  North America       560   2023-04-18   22.000000
170  North America      1300   2023-03-28   18.000000
174  North America      9000   2023-03-20    2.295918
179  North America     10000   2023-03-14   13.584117
189  North America       500   2023-03-01    4.000000
201  North America      2400   2023-02-17    5.000000
225  North America      1300   2023-02-07   15.000000
226  North America       500   2023-02-07    4.000000
227  North America       212   2023-02-07    9.000000
241  North America      2000   2023-01-31    7.000000
257  North America     12000   2023-01-20    6.000000
264  North America     10000   2023-01-18    5.000000
266  North America       275   2023-01-18   20.000000
274  North America       284   2023-01-17    3.000000
296  North America      8000   2023-01-04    2.000000
302  North America      4800   2023-01-01   10.000000
329  North America       180   2022-12-06   12.000000
337  North America      1250   2022-11-30    6.000000
348  North America     10000   2022-11-16    3.000000
349  North America      4100   2022-11-16    5.000000
371  North America     11000   2022-11-09   13.000000
385  North America       700   2022-11-03   13.000000
387  North America       550   2022-11-02   18.000000
395  North America       150   2022-10-28    0.044980
509  North America        60   2022-07-20    2.000000
544  North America       200   2022-06-29    4.000000
558  North America       300   2022-06-23    3.000000
615  North America       150   2022-05-17    1.000000
621  North America       270   2022-05-09   14.000000
649  North America      1000   2024-10-01    0.531915
655  North America      1800   2024-08-01   25.000000

     Company_Size_before_Layoffs  Company_Size_after_layoffs        Industry  \
0                           3500                        3150          Energy
4                           2045                        1820          Retail
8                           6625                        6360           Other
11                          3125                        3000          Travel
55                          2000                        1700        Security
57                         11580                       11001           Other
90                         20077                       19877  Transportation
95                           425                         323  Transportation
99                          2000                        1920       Education
106                         1800                        1710        Consumer
119                         1500                        1455         Finance
129                         7500                        6900           Other
135                         3125                        2625           Other
137                         1091                         971  Transportation
144                         4123                        3051  Transportation
146                         1200                        1020           Media
149                         2545                        1985     Real Estate
170                         7222                        5922  Transportation
174                       392000                      383000          Retail
179                        73615                       63615        Consumer
189                        12500                       12000           Other
201                        48000                       45600        Hardware
225                         8667                        7367           Other
226                        12500                       12000          Retail
227                         2356                        2144        Security
241                        28571                       26571         Finance
257                       200000                      188000        Consumer
264                       200000                      190000           Other
266                         1375                        1100  Transportation
274                         9467                        9183           Other
296                       400000                      392000          Retail
302                        48000                       43200        Hardware
329                         1500                        1320           Media
337                        20833                       19583            Food
348                       333333                      323333          Retail
349                        82000                       77900  Infrastructure
371                        84615                       73615        Consumer
385                         5385                        4685  Transportation
387                         3056                        2506     Real Estate
395                       333483                      333333          Retail
509                         3000                        2940  Transportation
544                         5000                        4800           Other
558                        10000                        9700           Media
615                        15000                       14850           Media
621                         1929                        1659  Transportation
649                       188000                      187000        Consumer
655                         7200                        5400           Other

        Stage Money_Raised_in_$_mil  Year       lat        lng
0    Post-IPO                  $116  2023  37.54827 -121.98857
4    Post-IPO                   $97  2023  40.71427  -74.00597
8    Post-IPO                 $1300  2023  37.77493 -122.41942
11   Post-IPO                    $3  2023  42.35843  -71.05977
55   Post-IPO                   $83  2023  33.74900  -84.38798
57   Post-IPO                  $748  2023  41.85003  -87.65005
90   Post-IPO                $25200  2023  37.77493 -122.41942
95   Post-IPO                  $340  2023  34.05223 -118.24368
99   Post-IPO                  $227  2023  37.35411 -121.95524
106  Series F                 $1300  2023  37.77493 -122.41942
119  Post-IPO                  $481  2023  40.71427  -74.00597
129  Post-IPO                 $1300  2023  37.77493 -122.41942
135  Post-IPO                 $1700  2023  37.77493 -122.41942
137  Post-IPO                 $1300  2023  40.71427  -74.00597
144  Post-IPO                 $4900  2023  37.77493 -122.41942
146  Post-IPO                  $696  2023  40.71427  -74.00597
149  Post-IPO                 $1900  2023  37.77493 -122.41942
170  Post-IPO                 $8300  2023  37.52966 -122.04024
174  Post-IPO                  $108  2023  47.60621 -122.33207
179  Post-IPO                $26000  2023  37.45383 -122.18219
189  Post-IPO                  $748  2023  41.85003  -87.65005
201  Post-IPO                   $50  2023  43.61350 -116.20345
225  Post-IPO                  $276  2023  37.33939 -121.89496
226  Post-IPO                 $1200  2023  37.33939 -121.89496
227  Post-IPO                   $83  2023  33.74900  -84.38798
241  Post-IPO                  $216  2023  37.33939 -121.89496
257  Post-IPO                   $26  2023  37.38605 -122.08385
264  Post-IPO                    $1  2023  47.60621 -122.33207
266  Post-IPO                  1300  2023  40.71427  -74.00597
274  Post-IPO                 $1300  2023  37.77493 -122.41942
296  Post-IPO                  $108  2023  47.60621 -122.33207
302  Post-IPO                   $50  2023  43.61350 -116.20345
329  Post-IPO                  $696  2022  40.71427  -74.00597
337  Post-IPO                 $2500  2022  37.77493 -122.41942
348  Post-IPO                  $108  2022  47.60621 -122.33207
349  Post-IPO                    $2  2022  37.33939 -121.89496
371  Post-IPO                $26000  2022  37.45383 -122.18219
385  Post-IPO                 $4900  2022  37.77493 -122.41942
387  Post-IPO                  1900  2022  37.77493 -122.41942
395  Post-IPO                  $108  2022  47.60621 -122.33207
509  Post-IPO                 $4900  2022  37.77493 -122.41942
544  Post-IPO                 $1300  2022  37.77493 -122.41942
558  Post-IPO               $121900  2022  37.22661 -121.97468
615  Post-IPO               $121900  2022  37.22661 -121.97468
621  Post-IPO                  1300  2022  40.71427  -74.00597
649  Post-IPO                   $26  2024  37.38605 -122.08385
655  Post-IPO                 $1300  2024  37.77493 -122.41942

/var/folders/l8/r1c1xr7142l1b6v2sys1fw300000gn/T/ipykernel_88282/1454057961.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_layoff_df['Company'] = filtered_layoff_df['Company'].replace(replacement_mapping)

In [106]:

df_extracted = filtered_layoff_df[['#','Company', 'Industry', 'Company_Size_after_layoffs', 'Company_Size_before_Layoffs','Location_HQ']].copy()


df_extracted.columns = ['CompanyID','CompanyName', 'Description', 'SizeOfCompany', 'TotalEmployee','Location']

print(df_extracted)

     CompanyID                    CompanyName     Description  SizeOfCompany  \
0            6             Enphase Energy Inc          Energy           3150
4           21                       Etsy Inc          Retail           1820
8           56             Unity Software Inc           Other           6360
11          91                Tripadvisor Inc          Travel           3000
55         311               SecureWorks Corp        Security           1700
57         328       Thoughtworks Holding Inc           Other          11001
90         504          Uber Technologies Inc  Transportation          19877
95         530                    TrueCar Inc  Transportation            323
99         540                      Chegg Inc       Education           1920
106        562                     Reddit Inc        Consumer           1710
119        628                   Lemonade Inc         Finance           1455
129        667             Unity Software Inc           Other           6900
135        688                    Dropbox Inc           Other           2625
137        690                      Vroom Inc  Transportation            971
144        709                       LYFT Inc  Transportation           3051
146        712                   Buzzfeed Inc           Media           1020
149        721      Opendoor Technologies Inc     Real Estate           1985
170        800                Lucid Group Inc  Transportation           5922
174        829                 Amazon.com Inc          Retail         383000
179        846             Meta Platforms Inc        Consumer          63615
189        895       Thoughtworks Holding Inc           Other          12000
201        953          Micron Technology Inc        Hardware          45600
225       1025  Zoom Video Communications Inc           Other           7367
226       1026                       eBay Inc          Retail          12000
227       1027               SecureWorks Corp        Security           2144
241       1084            PayPal Holdings Inc         Finance          26571
257       1171           Alphabet Inc Class C        Consumer         188000
264       1204                 Microsoft Corp           Other         190000
266       1207                      Vroom Inc  Transportation           1100
274       1229             Unity Software Inc           Other           9183
296       1346                 Amazon.com Inc          Retail         392000
302       1359          Micron Technology Inc        Hardware          43200
329       1461                   Buzzfeed Inc           Media           1320
337       1498                   DoorDash Inc            Food          19583
348       1586                 Amazon.com Inc          Retail         323333
349       1587              Cisco Systems Inc  Infrastructure          77900
371       1654             Meta Platforms Inc        Consumer          73615
385       1694                       LYFT Inc  Transportation           4685
387       1706      Opendoor Technologies Inc     Real Estate           2506
395       1735                 Amazon.com Inc          Retail         333333
509       2154                       LYFT Inc  Transportation           2940
544       2263             Unity Software Inc           Other           4800
558       2303                    Netflix Inc           Media           9700
615       2492                    Netflix Inc           Media          14850
621       2510                      Vroom Inc  Transportation           1659
649       3277           Alphabet Inc Class C        Consumer         187000
655       3285             Unity Software Inc           Other           5400

     TotalEmployee                Location
0             3500  San Francisco Bay Area
4             2045           New York City
8             6625  San Francisco Bay Area
11            3125                  Boston
55            2000                 Atlanta
57           11580                 Chicago
90           20077  San Francisco Bay Area
95             425             Los Angeles
99            2000  San Francisco Bay Area
106           1800  San Francisco Bay Area
119           1500           New York City
129           7500  San Francisco Bay Area
135           3125  San Francisco Bay Area
137           1091           New York City
144           4123  San Francisco Bay Area
146           1200           New York City
149           2545  San Francisco Bay Area
170           7222  San Francisco Bay Area
174         392000                 Seattle
179          73615  San Francisco Bay Area
189          12500                 Chicago
201          48000                   Boise
225           8667  San Francisco Bay Area
226          12500  San Francisco Bay Area
227           2356                 Atlanta
241          28571  San Francisco Bay Area
257         200000  San Francisco Bay Area
264         200000                 Seattle
266           1375           New York City
274           9467  San Francisco Bay Area
296         400000                 Seattle
302          48000                   Boise
329           1500           New York City
337          20833  San Francisco Bay Area
348         333333                 Seattle
349          82000  San Francisco Bay Area
371          84615  San Francisco Bay Area
385           5385  San Francisco Bay Area
387           3056  San Francisco Bay Area
395         333483                 Seattle
509           3000  San Francisco Bay Area
544           5000  San Francisco Bay Area
558          10000  San Francisco Bay Area
615          15000  San Francisco Bay Area
621           1929           New York City
649         188000  San Francisco Bay Area
655           7200  San Francisco Bay Area

In [107]:
df_extracted.to_csv('company_table.csv', index=False)

In [108]:
num_rows = len(df_extracted)
industry_ids = ['I' + str(np.random.randint(1, 1000)).zfill(3) for _ in range(num_rows)]
region_ids = ['R' + str(np.random.randint(1000, 2000)).zfill(4) for _ in range(num_rows)]

# Add IndustryID and RegionID to DataFrame
df_extracted['IndustryID'] = industry_ids
df_extracted['RegionID'] = region_ids

# Display the DataFrame
print(df_extracted)

     CompanyID                    CompanyName     Description  SizeOfCompany  \
0            6             Enphase Energy Inc          Energy           3150
4           21                       Etsy Inc          Retail           1820
8           56             Unity Software Inc           Other           6360
11          91                Tripadvisor Inc          Travel           3000
55         311               SecureWorks Corp        Security           1700
57         328       Thoughtworks Holding Inc           Other          11001
90         504          Uber Technologies Inc  Transportation          19877
95         530                    TrueCar Inc  Transportation            323
99         540                      Chegg Inc       Education           1920
106        562                     Reddit Inc        Consumer           1710
119        628                   Lemonade Inc         Finance           1455
129        667             Unity Software Inc           Other           6900
135        688                    Dropbox Inc           Other           2625
137        690                      Vroom Inc  Transportation            971
144        709                       LYFT Inc  Transportation           3051
146        712                   Buzzfeed Inc           Media           1020
149        721      Opendoor Technologies Inc     Real Estate           1985
170        800                Lucid Group Inc  Transportation           5922
174        829                 Amazon.com Inc          Retail         383000
179        846             Meta Platforms Inc        Consumer          63615
189        895       Thoughtworks Holding Inc           Other          12000
201        953          Micron Technology Inc        Hardware          45600
225       1025  Zoom Video Communications Inc           Other           7367
226       1026                       eBay Inc          Retail          12000
227       1027               SecureWorks Corp        Security           2144
241       1084            PayPal Holdings Inc         Finance          26571
257       1171           Alphabet Inc Class C        Consumer         188000
264       1204                 Microsoft Corp           Other         190000
266       1207                      Vroom Inc  Transportation           1100
274       1229             Unity Software Inc           Other           9183
296       1346                 Amazon.com Inc          Retail         392000
302       1359          Micron Technology Inc        Hardware          43200
329       1461                   Buzzfeed Inc           Media           1320
337       1498                   DoorDash Inc            Food          19583
348       1586                 Amazon.com Inc          Retail         323333
349       1587              Cisco Systems Inc  Infrastructure          77900
371       1654             Meta Platforms Inc        Consumer          73615
385       1694                       LYFT Inc  Transportation           4685
387       1706      Opendoor Technologies Inc     Real Estate           2506
395       1735                 Amazon.com Inc          Retail         333333
509       2154                       LYFT Inc  Transportation           2940
544       2263             Unity Software Inc           Other           4800
558       2303                    Netflix Inc           Media           9700
615       2492                    Netflix Inc           Media          14850
621       2510                      Vroom Inc  Transportation           1659
649       3277           Alphabet Inc Class C        Consumer         187000
655       3285             Unity Software Inc           Other           5400

     TotalEmployee                Location IndustryID RegionID
0             3500  San Francisco Bay Area       I434    R1993
4             2045           New York City       I395    R1046
8             6625  San Francisco Bay Area       I078    R1249
11            3125                  Boston       I522    R1084
55            2000                 Atlanta       I890    R1428
57           11580                 Chicago       I711    R1974
90           20077  San Francisco Bay Area       I424    R1455
95             425             Los Angeles       I674    R1995
99            2000  San Francisco Bay Area       I804    R1558
106           1800  San Francisco Bay Area       I455    R1342
119           1500           New York City       I835    R1929
129           7500  San Francisco Bay Area       I191    R1276
135           3125  San Francisco Bay Area       I398    R1278
137           1091           New York City       I688    R1579
144           4123  San Francisco Bay Area       I686    R1955
146           1200           New York City       I243    R1684
149           2545  San Francisco Bay Area       I633    R1851
170           7222  San Francisco Bay Area       I987    R1004
174         392000                 Seattle       I485    R1415
179          73615  San Francisco Bay Area       I875    R1199
189          12500                 Chicago       I556    R1815
201          48000                   Boise       I813    R1926
225           8667  San Francisco Bay Area       I844    R1448
226          12500  San Francisco Bay Area       I546    R1509
227           2356                 Atlanta       I369    R1752
241          28571  San Francisco Bay Area       I171    R1335
257         200000  San Francisco Bay Area       I644    R1438
264         200000                 Seattle       I398    R1027
266           1375           New York City       I747    R1422
274           9467  San Francisco Bay Area       I235    R1769
296         400000                 Seattle       I175    R1233
302          48000                   Boise       I310    R1304
329           1500           New York City       I107    R1481
337          20833  San Francisco Bay Area       I317    R1213
348         333333                 Seattle       I941    R1807
349          82000  San Francisco Bay Area       I498    R1716
371          84615  San Francisco Bay Area       I994    R1963
385           5385  San Francisco Bay Area       I607    R1263
387           3056  San Francisco Bay Area       I986    R1957
395         333483                 Seattle       I132    R1203
509           3000  San Francisco Bay Area       I839    R1069
544           5000  San Francisco Bay Area       I417    R1093
558          10000  San Francisco Bay Area       I235    R1238
615          15000  San Francisco Bay Area       I711    R1451
621           1929           New York City       I071    R1360
649         188000  San Francisco Bay Area       I350    R1746
655           7200  San Francisco Bay Area       I799    R1830

In [109]:
# Grouping by 'CompanyName' and selecting first occurrence of each group
company_groups = df_extracted.groupby('CompanyName').first()

# Creating a dictionary mapping CompanyName to IndustryID and RegionID
company_mapping = {}
for index, row in company_groups.iterrows():
    company_mapping[index] = (row['IndustryID'])

# Function to assign the same IndustryID and RegionID to rows with the same CompanyName
def assign_same_ids(row):
    industry_id = company_mapping.get(row['CompanyName'], (None))
    row['IndustryID'] = industry_id
    return row

# Applying the function to each row in the DataFrame
df_extracted = df_extracted.apply(assign_same_ids, axis=1)

# Displaying the updated DataFrame
print(df_extracted)

     CompanyID                    CompanyName     Description  SizeOfCompany  \
0            6             Enphase Energy Inc          Energy           3150
4           21                       Etsy Inc          Retail           1820
8           56             Unity Software Inc           Other           6360
11          91                Tripadvisor Inc          Travel           3000
55         311               SecureWorks Corp        Security           1700
57         328       Thoughtworks Holding Inc           Other          11001
90         504          Uber Technologies Inc  Transportation          19877
95         530                    TrueCar Inc  Transportation            323
99         540                      Chegg Inc       Education           1920
106        562                     Reddit Inc        Consumer           1710
119        628                   Lemonade Inc         Finance           1455
129        667             Unity Software Inc           Other           6900
135        688                    Dropbox Inc           Other           2625
137        690                      Vroom Inc  Transportation            971
144        709                       LYFT Inc  Transportation           3051
146        712                   Buzzfeed Inc           Media           1020
149        721      Opendoor Technologies Inc     Real Estate           1985
170        800                Lucid Group Inc  Transportation           5922
174        829                 Amazon.com Inc          Retail         383000
179        846             Meta Platforms Inc        Consumer          63615
189        895       Thoughtworks Holding Inc           Other          12000
201        953          Micron Technology Inc        Hardware          45600
225       1025  Zoom Video Communications Inc           Other           7367
226       1026                       eBay Inc          Retail          12000
227       1027               SecureWorks Corp        Security           2144
241       1084            PayPal Holdings Inc         Finance          26571
257       1171           Alphabet Inc Class C        Consumer         188000
264       1204                 Microsoft Corp           Other         190000
266       1207                      Vroom Inc  Transportation           1100
274       1229             Unity Software Inc           Other           9183
296       1346                 Amazon.com Inc          Retail         392000
302       1359          Micron Technology Inc        Hardware          43200
329       1461                   Buzzfeed Inc           Media           1320
337       1498                   DoorDash Inc            Food          19583
348       1586                 Amazon.com Inc          Retail         323333
349       1587              Cisco Systems Inc  Infrastructure          77900
371       1654             Meta Platforms Inc        Consumer          73615
385       1694                       LYFT Inc  Transportation           4685
387       1706      Opendoor Technologies Inc     Real Estate           2506
395       1735                 Amazon.com Inc          Retail         333333
509       2154                       LYFT Inc  Transportation           2940
544       2263             Unity Software Inc           Other           4800
558       2303                    Netflix Inc           Media           9700
615       2492                    Netflix Inc           Media          14850
621       2510                      Vroom Inc  Transportation           1659
649       3277           Alphabet Inc Class C        Consumer         187000
655       3285             Unity Software Inc           Other           5400

     TotalEmployee                Location IndustryID RegionID
0             3500  San Francisco Bay Area       I434    R1993
4             2045           New York City       I395    R1046
8             6625  San Francisco Bay Area       I078    R1249
11            3125                  Boston       I522    R1084
55            2000                 Atlanta       I890    R1428
57           11580                 Chicago       I711    R1974
90           20077  San Francisco Bay Area       I424    R1455
95             425             Los Angeles       I674    R1995
99            2000  San Francisco Bay Area       I804    R1558
106           1800  San Francisco Bay Area       I455    R1342
119           1500           New York City       I835    R1929
129           7500  San Francisco Bay Area       I078    R1276
135           3125  San Francisco Bay Area       I398    R1278
137           1091           New York City       I688    R1579
144           4123  San Francisco Bay Area       I686    R1955
146           1200           New York City       I243    R1684
149           2545  San Francisco Bay Area       I633    R1851
170           7222  San Francisco Bay Area       I987    R1004
174         392000                 Seattle       I485    R1415
179          73615  San Francisco Bay Area       I875    R1199
189          12500                 Chicago       I711    R1815
201          48000                   Boise       I813    R1926
225           8667  San Francisco Bay Area       I844    R1448
226          12500  San Francisco Bay Area       I546    R1509
227           2356                 Atlanta       I890    R1752
241          28571  San Francisco Bay Area       I171    R1335
257         200000  San Francisco Bay Area       I644    R1438
264         200000                 Seattle       I398    R1027
266           1375           New York City       I688    R1422
274           9467  San Francisco Bay Area       I078    R1769
296         400000                 Seattle       I485    R1233
302          48000                   Boise       I813    R1304
329           1500           New York City       I243    R1481
337          20833  San Francisco Bay Area       I317    R1213
348         333333                 Seattle       I485    R1807
349          82000  San Francisco Bay Area       I498    R1716
371          84615  San Francisco Bay Area       I875    R1963
385           5385  San Francisco Bay Area       I686    R1263
387           3056  San Francisco Bay Area       I633    R1957
395         333483                 Seattle       I485    R1203
509           3000  San Francisco Bay Area       I686    R1069
544           5000  San Francisco Bay Area       I078    R1093
558          10000  San Francisco Bay Area       I235    R1238
615          15000  San Francisco Bay Area       I235    R1451
621           1929           New York City       I688    R1360
649         188000  San Francisco Bay Area       I644    R1746
655           7200  San Francisco Bay Area       I078    R1830

In [110]:
df_extracted.head(50)

,CompanyID,CompanyName,Description,SizeOfCompany,TotalEmployee,Location,IndustryID,RegionID
0,6,Enphase Energy Inc,Energy,3150,3500,San Francisco Bay Area,I434,R1993
4,21,Etsy Inc,Retail,1820,2045,New York City,I395,R1046
8,56,Unity Software Inc,Other,6360,6625,San Francisco Bay Area,I078,R1249
11,91,Tripadvisor Inc,Travel,3000,3125,Boston,I522,R1084
55,311,SecureWorks Corp,Security,1700,2000,Atlanta,I890,R1428
57,328,Thoughtworks Holding Inc,Other,11001,11580,Chicago,I711,R1974
90,504,Uber Technologies Inc,Transportation,19877,20077,San Francisco Bay Area,I424,R1455
95,530,TrueCar Inc,Transportation,323,425,Los Angeles,I674,R1995
99,540,Chegg Inc,Education,1920,2000,San Francisco Bay Area,I804,R1558
106,562,Reddit Inc,Consumer,1710,1800,San Francisco Bay Area,I455,R1342
119,628,Lemonade Inc,Finance,1455,1500,New York City,I835,R1929
129,667,Unity Software Inc,Other,6900,7500,San Francisco Bay Area,I078,R1276
135,688,Dropbox Inc,Other,2625,3125,San Francisco Bay Area,I398,R1278
137,690,Vroom Inc,Transportation,971,1091,New York City,I688,R1579
144,709,LYFT Inc,Transportation,3051,4123,San Francisco Bay Area,I686,R1955
146,712,Buzzfeed Inc,Media,1020,1200,New York City,I243,R1684
149,721,Opendoor Technologies Inc,Real Estate,1985,2545,San Francisco Bay Area,I633,R1851
170,800,Lucid Group Inc,Transportation,5922,7222,San Francisco Bay Area,I987,R1004
174,829,Amazon.com Inc,Retail,383000,392000,Seattle,I485,R1415
179,846,Meta Platforms Inc,Consumer,63615,73615,San Francisco Bay Area,I875,R1199
189,895,Thoughtworks Holding Inc,Other,12000,12500,Chicago,I711,R1815
201,953,Micron Technology Inc,Hardware,45600,48000,Boise,I813,R1926
225,1025,Zoom Video Communications Inc,Other,7367,8667,San Francisco Bay Area,I844,R1448
226,1026,eBay Inc,Retail,12000,12500,San Francisco Bay Area,I546,R1509
227,1027,SecureWorks Corp,Security,2144,2356,Atlanta,I890,R1752
241,1084,PayPal Holdings Inc,Finance,26571,28571,San Francisco Bay Area,I171,R1335
257,1171,Alphabet Inc Class C,Consumer,188000,200000,San Francisco Bay Area,I644,R1438
264,1204,Microsoft Corp,Other,190000,200000,Seattle,I398,R1027
266,1207,Vroom Inc,Transportation,1100,1375,New York City,I688,R1422
274,1229,Unity Software Inc,Other,9183,9467,San Francisco Bay Area,I078,R1769
296,1346,Amazon.com Inc,Retail,392000,400000,Seattle,I485,R1233
302,1359,Micron Technology Inc,Hardware,43200,48000,Boise,I813,R1304
329,1461,Buzzfeed Inc,Media,1320,1500,New York City,I243,R1481
337,1498,DoorDash Inc,Food,19583,20833,San Francisco Bay Area,I317,R1213
348,1586,Amazon.com Inc,Retail,323333,333333,Seattle,I485,R1807
349,1587,Cisco Systems Inc,Infrastructure,77900,82000,San Francisco Bay Area,I498,R1716
371,1654,Meta Platforms Inc,Consumer,73615,84615,San Francisco Bay Area,I875,R1963
385,1694,LYFT Inc,Transportation,4685,5385,San Francisco Bay Area,I686,R1263
387,1706,Opendoor Technologies Inc,Real Estate,2506,3056,San Francisco Bay Area,I633,R1957
395,1735,Amazon.com Inc,Retail,333333,333483,Seattle,I485,R1203
509,2154,LYFT Inc,Transportation,2940,3000,San Francisco Bay Area,I686,R1069
544,2263,Unity Software Inc,Other,4800,5000,San Francisco Bay Area,I078,R1093
558,2303,Netflix Inc,Media,9700,10000,San Francisco Bay Area,I235,R1238
615,2492,Netflix Inc,Media,14850,15000,San Francisco Bay Area,I235,R1451
621,2510,Vroom Inc,Transportation,1659,1929,New York City,I688,R1360
649,3277,Alphabet Inc Class C,Consumer,187000,188000,San Francisco Bay Area,I644,R1746
655,3285,Unity Software Inc,Other,5400,7200,San Francisco Bay Area,I078,R1830

In [111]:
df_extracted.to_csv('company_table.csv', index=False)